#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Bioindustrial-Park: BioSTEAM's Premier Biorefinery Models and Results
# Copyright (C) 2021-, Sarang Bhagwat <sarangbhagwat.developer@gmail.com>
#
# This module is under the UIUC open-source license. See
# github.com/BioSTEAMDevelopmentGroup/biosteam/blob/master/LICENSE.txt
# for license details.
"""
Consolidated scenario loading -- the single source of truth for every
scenario's baseline kinetics + uncertainty distributions (from its
parameter-distributions workbook) and baseline feeding strategy.

A "scenario" = (workbook: baseline kinetics + distributions)
             + (feeding strategy: max_n_spikes, threshold_conc, target_conc)
             + (expected pins for the smoke tests).

`load_scenario(scenario)` runs the recipe formerly duplicated across
smoke tests 1-8 and the BO driver against the ALREADY-LOADED model
(the caller calls `isobutanol.load(...)` first, choosing the separation
configuration). It does NOT call `isobutanol.load()`.

Registered as a submodule in `__init__.py`; model/system objects and
`kinetic_optimization` are imported lazily (only valid after load()), so
importing this module is build-free.
"""
import os
import math
from dataclasses import dataclass

__all__ = ('ScenarioSpec', 'SCENARIOS', 'load_scenario',
           'assert_MPSPs_pinned', 'assert_MPSPs_stable',
           'assert_objective_reproduced')

_PKG_DIR = os.path.dirname(os.path.abspath(__file__))
_WORKBOOK_DIR = os.path.join(_PKG_DIR, 'analyses', 'full',
                             'parameter_distributions')


@dataclass(frozen=True)
class ScenarioSpec:
    """One scenario. `workbook` is a bare filename under
    analyses/full/parameter_distributions/. `expected` pins the smoke-test
    MPSPs, {'ethanol': float, 'isobutanol': float} (nan for an empty
    product). For opt_* scenarios `objective_name` names an
    OBJECTIVE_REGISTRY key and `objective_value` its reproduced value.
    `spike_conc` / `stage_1_max_x` are None for every current scenario
    (load() defaults 600 g/L / 5.0 g/L); a non-None value is not yet
    supported (see load_scenario). `burden_default` is the enzyme-burden
    policy load_scenario applies when its own `burden` kwarg is None."""
    name: str
    workbook: str
    max_n_spikes: int
    threshold_conc: float
    target_conc: float
    expected: dict
    objective_name: str = None
    objective_value: float = None
    objective_tol: float = 0.02
    spike_conc: float = None
    stage_1_max_x: float = None
    burden_default: bool = True

    @property
    def workbook_path(self):
        return os.path.join(_WORKBOOK_DIR, self.workbook)


SCENARIOS = {
    'A': ScenarioSpec(
        name='A',
        workbook='parameter-distributions_corn_IBO_EtOH_A.xlsx',
        max_n_spikes=16, threshold_conc=217.125, target_conc=221.25,
        expected={'ethanol': 0.86233, 'isobutanol': math.nan}),
    'B': ScenarioSpec(
        name='B',
        workbook='parameter-distributions_corn_IBO_EtOH_B.xlsx',
        max_n_spikes=0, threshold_conc=34.25, target_conc=140.0,
        expected={'ethanol': 0.59698, 'isobutanol': 1.2808},
        burden_default=False),
    # opt_* scenarios reproduce the best-objective trial of the last five
    # metabolic_minimal_subset kinetic-optimization studies. The workbooks
    # (the trials' kinetic parameter sets) were generated by
    # analyses/build_opt_scenario_workbooks.py (ask-first) -- see the
    # implementation plan, Task 6.
    # burden_default=True on every opt_* scenario (Task 6): the workbooks
    # store INTENDED (non-derated) k_7/k_8, and are simulated under the
    # A-referenced enzyme burden (built from scenario A's kinetics, same as
    # any other scenario) which derates them at the load_simulate choke
    # point back to each trial's original (previously baked-in) operating
    # point.
    # RE-PINNED 2026-09-12 for nskinetics anaerobic_growth_mult 1.0 -> 0.75:
    # the expected MPSPs and objective_value below are the CURRENT live-model
    # outputs at these fixed workbook kinetics, NOT the studies' originally
    # recorded best-trial values. The trials were optimized under the old
    # (1.0) model, so their objectives degraded substantially under the new
    # model (e.g. opt_IRR IRR 0.23508 -> 0.19276, opt_IBO_titer titer
    # 102.10 -> 78.32 g/L, opt_EtOH_yield yield 0.48589 -> 0.33246); these
    # entries now serve as reproducibility/regression pins. Re-finding the
    # optima under the new model requires re-running the studies (ask-first).
    # RE-PINNED AGAIN 2026-09-12 for the DDGS-dryer acid split (spec
    # docs/superpowers/specs/2026-09-12-ddgs-dryer-acid-split-design.md):
    # D610 now splits the broth acids (acetic acid) 1.0 to its exhaust,
    # burned in X611, instead of selling them as DDGS mass, so every
    # scenario's TEA moves: A/B ethanol in the 4th significant figure
    # (A 0.86680 -> 0.86867, B 0.66834 -> 0.67182 / isobutanol 1.2976 ->
    # 1.3018), while the opt_* trace-product MPSPs move 2-5% and opt_IRR's
    # economic objective 0.19276 -> 0.18830 (all re-pinned above); the
    # titer/yield objectives are fermentation-side and unchanged. These
    # values are the pre-change baseline of the r16 Ehrlich split.
    # RE-PINNED 2026-09-13 for the r13 rate law (nskinetics a2b001c; see
    # docs/reports/r13-rate-law.md): acetolactate synthase r13 is now
    # Michaelis-Menten in pyruvate with K_13 = 0.10 g/L instead of a copy
    # of r3's Hill n=4 form with K_13 = 5e-7. B moved (ethanol 0.67182 ->
    # 0.60727 / isobutanol 1.3018 -> 1.2864, IRR 0.2042 -> 0.2153; the
    # branch split is now pyruvate-responsive and B's pyruvate pool rises
    # above the old Hill saturation point, so r13 gains share); the opt_*
    # pins moved < 1 % (their objectives: IRR 0.18830 -> 0.18717, IBO
    # titer 78.32 -> 78.43, IBO yield 0.25477 -> 0.25210, EtOH titer
    # 254.94 -> 255.03, EtOH yield 0.33246 -> 0.33242), except the
    # near-zero-IBO opt_EtOH_titer / opt_EtOH_yield isobutanol artifacts
    # (-1.79 -> -2.91, 493.6 -> 1442.7). A is unaffected (k_13 = 0).
    # RE-PINNED 2026-09-13 (second) for the r14-r16 rate laws (nskinetics
    # b61360e / 623ff6f; report nskinetics docs/reports/r14-r16-rate-laws-
    # and-affinity-anchoring.md): r16 is irreversible Michaelis-Menten in
    # KIV with no k_16r / K_16i terms (both inert at 0; the K_16i workbook
    # row was dropped), its redox coefficient 0.363 -> 0.138 $Red per g KIV
    # (r6's per-gram-acetaldehyde figure had been copied, 2.6x too large,
    # over-crediting qO2 and the aeration sizing), r14 charges one NADPH,
    # r13/r16 release CO2, and K_14/K_15/K_16 are anchored to the fitted
    # core (2.64e-4/2.64e-4/0.034 -> 0.017/0.080/0.27 g/L; workbook rows
    # +-20 %). B: ethanol 0.60727 -> 0.61216 / isobutanol 1.2864 -> 1.2948,
    # IRR 0.2153 -> 0.2124, IBO titer 28.8 -> 29.0 g/L (yield 0.206 ->
    # 0.207), EtOH 26.6 -> 26.3 g/L (yield 0.190 -> 0.188), tau 56.0 ->
    # 61.9 h (product split nearly unchanged; the longer batch is what
    # moves the MPSPs); the ethanol-only / re-gated B builds 1.6521 ->
    # 1.6814. opt_* objectives:
    # IRR 0.18717 -> 0.19294, IBO titer 78.43 -> 78.03, IBO yield 0.25210
    # -> 0.25041, EtOH titer 255.03 -> 258.54, EtOH yield 0.33242 ->
    # 0.33251; opt_EtOH_yield's near-zero-IBO isobutanol artifact 1442.7 ->
    # 1801.3. A is unaffected (k_13-k_16 = 0).
    # RE-PINNED 2026-09-13 (third) for the P508 detach (system.py load()):
    # corn's orphaned rectifier-bottoms pump P508 was still docked into
    # MX5, feeding the STALE build-time corn_EtOH_sys.simulate() rectifier
    # bottoms (~14,160 kg/hr, essentially water) into M501 / WWT on every
    # simulation -- a phantom WWT feed with no live source (found while
    # fixing the nskinetics fed-batch spike-feed mass balance, report
    # nskinetics docs/reports/fed-batch-spike-feed-reconciliation.md
    # section 6.5). Fermentation is untouched (every V406 outcome, tau,
    # spike count and the fermentation-side objectives reproduce to 7-9
    # sig figs); only WWT + facility sizing and hence the TEA move: A
    # 0.86867 -> 0.86233 (IRR 0.1210 -> 0.1260, TCI 142.8 -> 139.3 MM$), B
    # 0.61216 -> 0.59698 / isobutanol 1.2948 -> 1.2808 (IRR 0.2124 ->
    # 0.2177), ethanol-only / re-gated A 0.84508 -> 0.83855 (IRR 0.1469),
    # B 1.6814 -> 1.6625 (IRR still -inf). opt_* MPSPs moved 1-5 % (the
    # trace-product artifacts more: opt_EtOH_titer isobutanol -2.89 ->
    # -9.99, opt_EtOH_yield 1801.3 -> 1736.0); opt_IRR's economic objective
    # 0.19294 -> 0.19883, the titer / yield objectives unchanged (kept).
    'opt_IRR': ScenarioSpec(
        name='opt_IRR',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_IRR.xlsx',
        max_n_spikes=18, threshold_conc=286.7667298838977, target_conc=300.0,
        expected={'ethanol': 0.5833567657359908, 'isobutanol': 1.3738337646938537},
        objective_name='IRR', objective_value=0.19883197219016238),
    'opt_IBO_titer': ScenarioSpec(
        name='opt_IBO_titer',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_IBO_titer.xlsx',
        max_n_spikes=39, threshold_conc=219.5386688951894, target_conc=300.0,
        expected={'ethanol': 11.790246445479358, 'isobutanol': 1.949578209995902},
        objective_name='IBO titer', objective_value=78.02972433254396),
    'opt_IBO_yield': ScenarioSpec(
        name='opt_IBO_yield',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_IBO_yield.xlsx',
        max_n_spikes=0, threshold_conc=270.0889834284513, target_conc=300.0,
        expected={'ethanol': -0.31264213251225687, 'isobutanol': 1.3863174771658522},
        objective_name='IBO yield', objective_value=0.2504124829470104),
    'opt_EtOH_titer': ScenarioSpec(
        name='opt_EtOH_titer',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_EtOH_titer.xlsx',
        max_n_spikes=35, threshold_conc=253.62164932574294, target_conc=300.0,
        expected={'ethanol': 0.8253953367021405, 'isobutanol': -9.991976723079743},
        objective_name='EtOH titer', objective_value=258.54485489699516),
    'opt_EtOH_yield': ScenarioSpec(
        name='opt_EtOH_yield',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_EtOH_yield.xlsx',
        max_n_spikes=22, threshold_conc=295.08474402550377, target_conc=300.0,
        expected={'ethanol': 1.0490744642447762, 'isobutanol': 1736.0469191469772},
        objective_name='EtOH yield', objective_value=0.3325081955440208),
}


def _handles():
    """Live model/system handles. Valid only after isobutanol.load()."""
    from biorefineries import isobutanol
    m = isobutanol.models
    model = m.models_EtOH_IBO_corn.model
    return dict(model=model,
                namespace_dict=m.namespace_dict,
                fbs_spec=m.fbs_spec,
                model_specification=model.specification,
                solve_TEA=isobutanol.system.solve_TEA,
                V406=model.system.flowsheet.V406,
                tea=model.system.TEA)


#: Cached scenario-A reference kinetics (the burden's wild-type calibration
#: point; native pools inert there). Populated once per kernel from the live
#: model after the A workbook is applied. A's kinetics are fixed within a
#: process, so caching is safe.
_A_REFERENCE = [None]


def _load_workbook(model, spec, h):
    """Apply a scenario workbook's Baseline column to the live model
    (kinetics + distributions), matching the existing load_scenario recipe."""
    model.parameters = ()
    model.load_parameter_distributions(spec.workbook_path, h['namespace_dict'])
    model.metrics_at_baseline()     # workbook Baseline column SETS kinetics


def _snapshot_kinetics(h):
    """The live kinetic parameters ({name: value}) off r_te, via the same
    reader the optimizer uses (kinetic_optimization.discover_kinetic_parameters)."""
    from biorefineries.isobutanol import kinetic_optimization as ko
    r_te = h['V406'].nsk_kinetic_model._te
    return ko.discover_kinetic_parameters(r_te)


def _scenario_A_reference(model, h):
    """Scenario A's full live kinetics, cached. On a cache miss, apply the A
    workbook and snapshot (this leaves the model on A; the caller re-applies
    the requested scenario afterwards)."""
    if _A_REFERENCE[0] is None:
        _load_workbook(model, SCENARIOS['A'], h)
        _A_REFERENCE[0] = _snapshot_kinetics(h)
    return _A_REFERENCE[0]


def load_scenario(scenario, *, apply=True, burden=None):
    """Load `scenario`'s baseline kinetics + distributions from its
    workbook, set the baseline feeding strategy, install the enzyme burden
    per policy, and (when apply=True) run one baseline `model_specification`.
    Returns a bundle the caller reuses for its stability loop. Requires the
    model to be built already (isobutanol.load(...)).

    `burden`: None -> the scenario's burden_default; True/False overrides.
    When effectively on, the enzyme BurdenModel is built from SCENARIO A's
    kinetics (the wild-type calibration where native pools are inert) --
    NOT from this scenario's own baseline -- and installed via
    system.set_active_burden, so the load_simulate choke point derates
    k_7/k_8 for every simulation of this scenario. If the scenario's own
    baseline point is over the proteome cap under that burden (e.g. scenario
    B's Ehrlich constants), a ValueError is raised telling the caller to
    pass burden=False."""
    if scenario not in SCENARIOS:
        raise ValueError(f'scenario {scenario!r} not in SCENARIOS: '
                         f'{sorted(SCENARIOS)}')
    spec = SCENARIOS[scenario]
    burden_on = spec.burden_default if burden is None else bool(burden)
    h = _handles()
    model = h['model']

    # Snapshot the scenario-A burden reference BEFORE loading a non-A
    # workbook (cache miss loads A, then we overwrite with the request).
    A_reference = _scenario_A_reference(model, h) if burden_on else None

    _load_workbook(model, spec, h)

    h['fbs_spec'].max_n_spikes = spec.max_n_spikes
    if spec.spike_conc is not None or spec.stage_1_max_x is not None:
        raise NotImplementedError(
            'load_scenario does not yet override spike_conc / stage_1_max_x; '
            'every registered scenario pins them at the load() defaults '
            '(600 g/L / 5.0 g/L).')
    feeding_kwargs = dict(threshold_conc=spec.threshold_conc,
                          target_conc=spec.target_conc)

    from biorefineries.isobutanol import system as _system
    burden_model = None
    if burden_on:
        from biorefineries.isobutanol import enzyme_burden as eb
        burden_model = eb.BurdenModel.from_reference(A_reference)
        point = _snapshot_kinetics(h)          # this scenario's baseline point
        result = burden_model.evaluate(point)
        if not result.feasible:
            raise ValueError(
                f'scenario {scenario!r} baseline is over the enzyme-burden '
                f'proteome cap (Phi_M {result.Phi_M:.4f} >= F_flex '
                f'{result.F_flex:.4f} g/gDCW) against the scenario-A '
                'reference; it cannot be simulated with the burden on. Pass '
                'burden=False to load it burden-free.')
        _system.set_active_burden(burden_model)
    else:
        _system.set_active_burden(None)

    if apply:
        h['model_specification'](**feeding_kwargs)

    return dict(spec=spec, feeding_kwargs=feeding_kwargs,
                expected=spec.expected, model=model,
                model_specification=h['model_specification'],
                solve_TEA=h['solve_TEA'], fbs_spec=h['fbs_spec'],
                namespace_dict=h['namespace_dict'], V406=h['V406'],
                tea=h['tea'], burden_model=burden_model, burden_on=burden_on)


def assert_MPSPs_pinned(expected, current, sim_number, rel_tol=0.01):
    """Verify current MPSPs against pinned baselines (within rel_tol; nan
    stays nan). Pins live in the SCENARIOS registry."""
    for ID, ref in expected.items():
        cur = current['MPSPs'][ID]
        if math.isnan(ref):
            assert math.isnan(cur), \
                f'sim {sim_number}: {ID} MPSP {cur} expected nan (empty product)'
        else:
            assert abs(cur - ref)/abs(ref) < rel_tol, \
                (f'sim {sim_number}: {ID} MPSP {cur} not within rel tol '
                 f'{rel_tol} of pinned {ref}')


def assert_MPSPs_stable(reference, current, sim_number, rel_tol=5e-3):
    """Verify current MPSPs match the first simulation's to ~3 sig figs
    (relative drift < rel_tol; nan stays nan)."""
    for ID, ref in reference['MPSPs'].items():
        cur = current['MPSPs'][ID]
        if math.isnan(ref) or math.isnan(cur):
            assert math.isnan(ref) and math.isnan(cur), \
                f'sim {sim_number}: {ID} MPSP {cur} vs first-sim {ref} (nan mismatch)'
        else:
            assert abs(cur - ref)/abs(ref) < rel_tol, \
                (f'sim {sim_number}: {ID} MPSP {cur} drifted from first-sim '
                 f'value {ref} beyond rel tol {rel_tol}')


def assert_objective_reproduced(spec, results, bundle, sim_number, rel_tol=None):
    """For an opt_* scenario, recompute the study's objective from the
    current simulated model state (via kinetic_optimization.OBJECTIVE_REGISTRY,
    the exact study definition) and verify it reproduces the best trial's
    recorded value. No-op for scenarios without an objective (A/B)."""
    if spec.objective_name is None:
        return
    tol = spec.objective_tol if rel_tol is None else rel_tol
    from biorefineries.isobutanol import kinetic_optimization as ko
    getter = ko.OBJECTIVE_REGISTRY[spec.objective_name]['getter']
    h = {'V406': bundle['V406'], 'tea': bundle['tea'],
         'latest_TEA_solution': results}
    value = getter(h)
    ref = spec.objective_value
    assert abs(value - ref)/abs(ref) < tol, \
        (f'sim {sim_number}: {spec.name} objective {spec.objective_name} '
         f'{value} not within rel tol {tol} of recorded best-trial {ref}')
