#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Bioindustrial-Park: BioSTEAM's Premier Biorefinery Models and Results
# Copyright (C) 2021-, Sarang Bhagwat <sarangbhagwat.developer@gmail.com>
#
# This module is under the UIUC open-source license. See
# github.com/BioSTEAMDevelopmentGroup/biosteam/blob/master/LICENSE.txt
# for license details.
"""
Consolidated scenario loading -- the single source of truth for every
scenario's baseline kinetics + uncertainty distributions (from its
parameter-distributions workbook) and baseline feeding strategy.

A "scenario" = (workbook: baseline kinetics + distributions)
             + (feeding strategy: max_n_spikes, threshold_conc, target_conc)
             + (expected pins for the smoke tests).

`load_scenario(scenario)` runs the recipe formerly duplicated across
smoke tests 1-8 and the BO driver against the ALREADY-LOADED model
(the caller calls `isobutanol.load(...)` first, choosing the separation
configuration). It does NOT call `isobutanol.load()`.

Registered as a submodule in `__init__.py`; model/system objects and
`kinetic_optimization` are imported lazily (only valid after load()), so
importing this module is build-free.
"""
import os
import math
from dataclasses import dataclass

__all__ = ('ScenarioSpec', 'SCENARIOS', 'load_scenario',
           'assert_MPSPs_pinned', 'assert_MPSPs_stable',
           'assert_objective_reproduced')

_PKG_DIR = os.path.dirname(os.path.abspath(__file__))
_WORKBOOK_DIR = os.path.join(_PKG_DIR, 'analyses', 'full',
                             'parameter_distributions')


@dataclass(frozen=True)
class ScenarioSpec:
    """One scenario. `workbook` is a bare filename under
    analyses/full/parameter_distributions/. `expected` pins the smoke-test
    MPSPs, {'ethanol': float, 'isobutanol': float} (nan for an empty
    product). For opt_* scenarios `objective_name` names an
    OBJECTIVE_REGISTRY key and `objective_value` its reproduced value.
    `spike_conc` / `stage_1_max_x` are None for every current scenario
    (load() defaults 600 g/L / 5.0 g/L); a non-None value is not yet
    supported (see load_scenario). `burden_default` is the enzyme-burden
    policy load_scenario applies when its own `burden` kwarg is None."""
    name: str
    workbook: str
    max_n_spikes: int
    threshold_conc: float
    target_conc: float
    expected: dict
    objective_name: str = None
    objective_value: float = None
    objective_tol: float = 0.02
    spike_conc: float = None
    stage_1_max_x: float = None
    burden_default: bool = True

    @property
    def workbook_path(self):
        return os.path.join(_WORKBOOK_DIR, self.workbook)


SCENARIOS = {
    'A': ScenarioSpec(
        name='A',
        workbook='parameter-distributions_corn_IBO_EtOH_A.xlsx',
        max_n_spikes=16, threshold_conc=217.125, target_conc=221.25,
        expected={'ethanol': 0.86604, 'isobutanol': math.nan}),
    'B': ScenarioSpec(
        name='B',
        workbook='parameter-distributions_corn_IBO_EtOH_B.xlsx',
        max_n_spikes=0, threshold_conc=34.25, target_conc=140.0,
        expected={'ethanol': 0.6642, 'isobutanol': 1.2924},
        burden_default=False),
    # opt_* scenarios reproduce the best-objective trial of the last five
    # metabolic_minimal_subset kinetic-optimization studies. Generated by
    # analyses/build_opt_scenario_workbooks.py (ask-first) -- see the
    # implementation plan, Task 6. Values pasted verbatim from its output.
    # burden_default=True on every opt_* scenario (Task 6): the workbooks
    # store INTENDED (non-derated) k_7/k_8, and are simulated under the
    # A-referenced enzyme burden (built from scenario A's kinetics, same as
    # any other scenario) which derates them at the load_simulate choke
    # point back to each trial's original (previously baked-in) operating
    # point -- so the pins below are unchanged (within tolerance) from the
    # burden-free-workbook generation.
    'opt_IRR': ScenarioSpec(
        name='opt_IRR',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_IRR.xlsx',
        max_n_spikes=18, threshold_conc=286.7667298838977, target_conc=300.0,
        expected={'ethanol': 0.4047796936667348, 'isobutanol': 1.2841892223671512},
        objective_name='IRR', objective_value=0.23508063927141376),
    'opt_IBO_titer': ScenarioSpec(
        name='opt_IBO_titer',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_IBO_titer.xlsx',
        max_n_spikes=39, threshold_conc=219.5386688951894, target_conc=300.0,
        expected={'ethanol': 6.799926063714883, 'isobutanol': 1.8282938457986915},
        objective_name='IBO titer', objective_value=102.09909483554148),
    'opt_IBO_yield': ScenarioSpec(
        name='opt_IBO_yield',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_IBO_yield.xlsx',
        max_n_spikes=0, threshold_conc=270.0889834284513, target_conc=300.0,
        expected={'ethanol': 6.644266101912991, 'isobutanol': 1.7100745581231347},
        objective_name='IBO yield', objective_value=0.26041000497319194),
    'opt_EtOH_titer': ScenarioSpec(
        name='opt_EtOH_titer',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_EtOH_titer.xlsx',
        max_n_spikes=35, threshold_conc=253.62164932574294, target_conc=300.0,
        expected={'ethanol': 0.8296066512540343, 'isobutanol': -2.490766444554419},
        objective_name='EtOH titer', objective_value=269.85590501617736),
    'opt_EtOH_yield': ScenarioSpec(
        name='opt_EtOH_yield',
        workbook='parameter-distributions_corn_IBO_EtOH_opt_EtOH_yield.xlsx',
        max_n_spikes=22, threshold_conc=295.08474402550377, target_conc=300.0,
        expected={'ethanol': 0.836632541778434, 'isobutanol': 5.105046675430989},
        objective_name='EtOH yield', objective_value=0.4858855784203736),
}


def _handles():
    """Live model/system handles. Valid only after isobutanol.load()."""
    from biorefineries import isobutanol
    m = isobutanol.models
    model = m.models_EtOH_IBO_corn.model
    return dict(model=model,
                namespace_dict=m.namespace_dict,
                fbs_spec=m.fbs_spec,
                model_specification=model.specification,
                solve_TEA=isobutanol.system.solve_TEA,
                V406=model.system.flowsheet.V406,
                tea=model.system.TEA)


#: Cached scenario-A reference kinetics (the burden's wild-type calibration
#: point; native pools inert there). Populated once per kernel from the live
#: model after the A workbook is applied. A's kinetics are fixed within a
#: process, so caching is safe.
_A_REFERENCE = [None]


def _load_workbook(model, spec, h):
    """Apply a scenario workbook's Baseline column to the live model
    (kinetics + distributions), matching the existing load_scenario recipe."""
    model.parameters = ()
    model.load_parameter_distributions(spec.workbook_path, h['namespace_dict'])
    model.metrics_at_baseline()     # workbook Baseline column SETS kinetics


def _snapshot_kinetics(h):
    """The live kinetic parameters ({name: value}) off r_te, via the same
    reader the optimizer uses (kinetic_optimization.discover_kinetic_parameters)."""
    from biorefineries.isobutanol import kinetic_optimization as ko
    r_te = h['V406'].nsk_kinetic_model._te
    return ko.discover_kinetic_parameters(r_te)


def _scenario_A_reference(model, h):
    """Scenario A's full live kinetics, cached. On a cache miss, apply the A
    workbook and snapshot (this leaves the model on A; the caller re-applies
    the requested scenario afterwards)."""
    if _A_REFERENCE[0] is None:
        _load_workbook(model, SCENARIOS['A'], h)
        _A_REFERENCE[0] = _snapshot_kinetics(h)
    return _A_REFERENCE[0]


def load_scenario(scenario, *, apply=True, burden=None):
    """Load `scenario`'s baseline kinetics + distributions from its
    workbook, set the baseline feeding strategy, install the enzyme burden
    per policy, and (when apply=True) run one baseline `model_specification`.
    Returns a bundle the caller reuses for its stability loop. Requires the
    model to be built already (isobutanol.load(...)).

    `burden`: None -> the scenario's burden_default; True/False overrides.
    When effectively on, the enzyme BurdenModel is built from SCENARIO A's
    kinetics (the wild-type calibration where native pools are inert) --
    NOT from this scenario's own baseline -- and installed via
    system.set_active_burden, so the load_simulate choke point derates
    k_7/k_8 for every simulation of this scenario. If the scenario's own
    baseline point is over the proteome cap under that burden (e.g. scenario
    B's Ehrlich constants), a ValueError is raised telling the caller to
    pass burden=False."""
    if scenario not in SCENARIOS:
        raise ValueError(f'scenario {scenario!r} not in SCENARIOS: '
                         f'{sorted(SCENARIOS)}')
    spec = SCENARIOS[scenario]
    burden_on = spec.burden_default if burden is None else bool(burden)
    h = _handles()
    model = h['model']

    # Snapshot the scenario-A burden reference BEFORE loading a non-A
    # workbook (cache miss loads A, then we overwrite with the request).
    A_reference = _scenario_A_reference(model, h) if burden_on else None

    _load_workbook(model, spec, h)

    h['fbs_spec'].max_n_spikes = spec.max_n_spikes
    if spec.spike_conc is not None or spec.stage_1_max_x is not None:
        raise NotImplementedError(
            'load_scenario does not yet override spike_conc / stage_1_max_x; '
            'every registered scenario pins them at the load() defaults '
            '(600 g/L / 5.0 g/L).')
    feeding_kwargs = dict(threshold_conc=spec.threshold_conc,
                          target_conc=spec.target_conc)

    from biorefineries.isobutanol import system as _system
    burden_model = None
    if burden_on:
        from biorefineries.isobutanol import enzyme_burden as eb
        burden_model = eb.BurdenModel.from_reference(A_reference)
        point = _snapshot_kinetics(h)          # this scenario's baseline point
        result = burden_model.evaluate(point)
        if not result.feasible:
            raise ValueError(
                f'scenario {scenario!r} baseline is over the enzyme-burden '
                f'proteome cap (Phi_M {result.Phi_M:.4f} >= F_flex '
                f'{result.F_flex:.4f} g/gDCW) against the scenario-A '
                'reference; it cannot be simulated with the burden on. Pass '
                'burden=False to load it burden-free.')
        _system.set_active_burden(burden_model)
    else:
        _system.set_active_burden(None)

    if apply:
        h['model_specification'](**feeding_kwargs)

    return dict(spec=spec, feeding_kwargs=feeding_kwargs,
                expected=spec.expected, model=model,
                model_specification=h['model_specification'],
                solve_TEA=h['solve_TEA'], fbs_spec=h['fbs_spec'],
                namespace_dict=h['namespace_dict'], V406=h['V406'],
                tea=h['tea'], burden_model=burden_model, burden_on=burden_on)


def assert_MPSPs_pinned(expected, current, sim_number, rel_tol=0.01):
    """Verify current MPSPs against pinned baselines (within rel_tol; nan
    stays nan). Pins live in the SCENARIOS registry."""
    for ID, ref in expected.items():
        cur = current['MPSPs'][ID]
        if math.isnan(ref):
            assert math.isnan(cur), \
                f'sim {sim_number}: {ID} MPSP {cur} expected nan (empty product)'
        else:
            assert abs(cur - ref)/abs(ref) < rel_tol, \
                (f'sim {sim_number}: {ID} MPSP {cur} not within rel tol '
                 f'{rel_tol} of pinned {ref}')


def assert_MPSPs_stable(reference, current, sim_number, rel_tol=5e-3):
    """Verify current MPSPs match the first simulation's to ~3 sig figs
    (relative drift < rel_tol; nan stays nan)."""
    for ID, ref in reference['MPSPs'].items():
        cur = current['MPSPs'][ID]
        if math.isnan(ref) or math.isnan(cur):
            assert math.isnan(ref) and math.isnan(cur), \
                f'sim {sim_number}: {ID} MPSP {cur} vs first-sim {ref} (nan mismatch)'
        else:
            assert abs(cur - ref)/abs(ref) < rel_tol, \
                (f'sim {sim_number}: {ID} MPSP {cur} drifted from first-sim '
                 f'value {ref} beyond rel tol {rel_tol}')


def assert_objective_reproduced(spec, results, bundle, sim_number, rel_tol=None):
    """For an opt_* scenario, recompute the study's objective from the
    current simulated model state (via kinetic_optimization.OBJECTIVE_REGISTRY,
    the exact study definition) and verify it reproduces the best trial's
    recorded value. No-op for scenarios without an objective (A/B)."""
    if spec.objective_name is None:
        return
    tol = spec.objective_tol if rel_tol is None else rel_tol
    from biorefineries.isobutanol import kinetic_optimization as ko
    getter = ko.OBJECTIVE_REGISTRY[spec.objective_name]['getter']
    h = {'V406': bundle['V406'], 'tea': bundle['tea'],
         'latest_TEA_solution': results}
    value = getter(h)
    ref = spec.objective_value
    assert abs(value - ref)/abs(ref) < tol, \
        (f'sim {sim_number}: {spec.name} objective {spec.objective_name} '
         f'{value} not within rel tol {tol} of recorded best-trial {ref}')
