# -*- coding: utf-8 -*-
"""
Created on Wed Oct 11 09:14:21 2023

@author: lavan
"""

import biosteam as bst
from biorefineries.oleochemicals.systems_baseline import F
from biorefineries.oleochemicals.chemicals_baseline import chems
from tea_baseline import TEA_baseline
from biorefineries.oleochemicals.prices_and_GWP_factors import prices_per_stream,GWP_per_stream
# from biosteam import preferences



def load_preferences_and_process_settings(T,flow_units,N,P_units,CE,
                                          indicator,electricity_price,
                                          electricity_EI,
                                          ):    
    bst.preferences.T = T
    bst.preferences.flow = flow_units
    bst.preferences.N = N
    bst.preferences.P = P_units
    bst.preferences.composition = True
    bst.preferences.light_mode()
    bst.preferences.save()
    bst.settings.CEPCI = CE  
    bst.settings.define_impact_indicator(key=indicator, units='kg*CO2e')
    bst.settings.set_electricity_CF(indicator,electricity_EI, electricity_EI,
                                    basis='kWhr', units='kg*CO2e')
    bst.settings.electricity_price = electricity_price
    lps = bst.HeatUtility.get_heating_agent('low_pressure_steam')
    mps = bst.HeatUtility.get_heating_agent('medium_pressure_steam')
    hps = bst.HeatUtility.get_heating_agent('high_pressure_steam')
    lps.T = 412.189 #default biosteam value
    mps.T = 233 + 273.15 #default biosteam value
    hps.T = 310+273.15 #saturated temperature, K [9]
    hps.P = 10000*1000 #saturated pressure at hps.T [9]
    cooling = bst.HeatUtility.get_cooling_agent('cooling_water')
    cooling.T = 28 + 273.15
    cooling.T_limit = cooling.T + 9
    for i in (lps, mps, hps, cooling):
        i.heat_transfer_price = i.regeneration_price = 0
    #Steam, cooling water, and chilled water are regenerated by on-site facilities. 
    #The regeneration and heat transfer prices given are accounted for by the capital cost.        
    bst.settings.get_agent('cooling_water').regeneration_price = 0
    bst.settings.get_agent('chilled_water').heat_transfer_price = 0


#Feedstock type can be either HoySoy or HoSun
def set_price_of_all_streams(feedstock_type): 
    kjoule_to_megajoule = 1/1000
    #Feedstock stream                    
    if feedstock_type == 'HoSun':
          print('see')
          F.crude_vegetable_oil.price = prices_per_stream['crude_vegetable_Hosun']
    else: F.crude_vegetable_oil.price = prices_per_stream['crude_vegetable_Hoysoy']
    for i in [ #streams defined inside the system
              F.stream.polystyrene_based_catalyst,
              F.stream.conc_HCl_for_resin_wash,
              #streams which are a part of the imported lipidcane transesterification unit
              F.stream.NaOH,
              F.catalyst,
              F.stream.methanol,
              F.stream.crude_methanol,
              F.stream.HCl]:
        i.price = prices_per_stream[i.ID]
    #Other streams
    for i in [F.crude_HO_oil_to_biodiesel,
              F.dihydroxylation_system,
              F.oxidative_cleavage_system,
              F.organic_phase_separation_and_catalyst_recovery,
              F.nonanoic_acid_fraction_separation,
              F.azelaic_acid_production,
              F.WWT901,
              F.BT801,
              F.CT701,
              F.CW701,
              F.PWT701
              ]:
            for j in i.ins:
                if j.ID in prices_per_stream.keys():
                    j.price = prices_per_stream[j.ID]
            for k in i.outs:
                if k.ID in prices_per_stream.keys():
                    k.price = prices_per_stream[k.ID]    
                  

def set_environmental_impact_of_all_streams(indicator,feedstock_type):
    #Feedstock stream                    
    if feedstock_type == 'HoSun':
          F.crude_vegetable_oil.characterization_factors[indicator] = GWP_per_stream['crude_vegetable_HoSun']
    else: F.crude_vegetable_oil.characterization_factors[indicator] = GWP_per_stream['crude_vegetable_Hoysoy']
    for i in [F.crude_HO_oil_to_biodiesel,
              F.dihydroxylation_system,
              F.oxidative_cleavage_system,
              F.organic_phase_separation_and_catalyst_recovery,
              F.nonanoic_acid_fraction_separation,
              F.azelaic_acid_production,
               F.BT801,
                F.CT701,
                F.CW701,
                F.PWT701,
                F.WWT901
              ]:
        for j in i.ins:                            
            if j.ID in GWP_per_stream.keys(): 
                j.characterization_factors[indicator]= GWP_per_stream[j.ID]            
        for k in i.outs:
            if k.ID in GWP_per_stream.keys():                
                k.characterization_factors[indicator] = GWP_per_stream[k.ID]
    for i in [ #streams defined inside the system
              F.stream.polystyrene_based_catalyst,
              F.stream.conc_HCl_for_resin_wash,
              #streams which are a part of the imported lipidcane transesterification unit
              F.stream.NaOH,
              F.stream.methanol,
              F.stream.catalyst,
              F.stream.HCl]:
        i.characterization_factors[indicator] = GWP_per_stream[i.ID]  
 

#Techno-economic analysis
def tea_azelaic_baseline(system,WC_over_FCI,operating_days,payrate,IRR):
    tea_azelaic_baseline = TEA_baseline(lang_factor=None,
    system = system,    
    IRR=IRR,  
    duration=(2023, 2053), #assumption, 30 years
    depreciation='MACRS7',#MARCS used in [1] was not available in Biosteam 
    income_tax=0.29+0.05,  #First value denotes federal corporate income tax for Illinois, second value denotes 
    #state income tax for Illinois [2],[3]
    operating_days=operating_days,  # Uncertain, can be varied
    construction_schedule=(0.4, 0.6),  #[1]
    startup_months=0,  # Based on conventional ethanol TEA assumptions in the tea module in bioindustrial park.
    #The assumptions are derived from [4]
    startup_FOCfrac=0,  # Based on ConventionalEthanolTEA class
    startup_salesfrac=0,  # Based on ConventionalEthanolTEA class
    startup_VOCfrac=0,  #Based on ConventionalEthanolTEA class
    WC_over_FCI=WC_over_FCI,  
    finance_interest=0,  #Based on ConventionalEthanolTEA class
    finance_years=0,  #Based on ConventionalEthanolTEA class
    finance_fraction=0,  #Based on ConventionalEthanolTEA class
    operating_labor_cost=5*5*payrate*operating_days/4,#Weekly pay rate based on [5].
    #Number of shifts based on [6]
    direct_supervisory_clerical_labor=0.18,#[6]
    OSBL_units=[ #Based on the designed system
                F.CW701,
                F.CT701,
                F.BT801,
                F.PWT701,
                F.ADP701,
                F.WWT901,
                # F.HXN901
                ],
    #DPI = IEC(1+ Factor for site preparation+ Factor for building construction)
    factor_for_site_prep=0.04,#[7]
    factor_for_building_construction=0.1,#[7]
    #TDC = DPI (1+ Factor for contingency fees)
    factor_for_contingency_fees =0.18,#[7]
    #Fixed capital investment (FCI) =  TDC (1+ Factor for land purchase+ 
    #Factor for royalties+ Factor for plant startup)
    factor_for_land_purchase = 0.02,#[7]
    factor_for_plant_startup = 0.10,#[7]
    factor_for_royalties = 0.02,#[7]
    #FCI_corrected = location_factor*FCI
    location_factor = 1.15,#[7]
    # FOC = FCI* (Factor for local taxes and insurance + 
    # Factor for maintenance and repairs + 
    # Factor for operating supplies + Factor for plant overhead + 
    # Factor for administration costs ) + OLC *(Factor for direct supervisory and clerical cost + 
    # Factor for laboratory charges + Factor for administrative costs + Factor for plant overhead costs)
    factor_local_taxes_and_insurance=0.1,#0.1*FCI  [8],
    factor_maintenance_and_repairs=0.06, #0.06*FCI,range:(0.02-0.1)*FCI[8] 
    factor_operating_supplies=0.009, #0.009*FCI,range:(0.1-0.2)*FCI[8]
    factor_laboratory_charges=0.15,  #0.15*operating_labor_cost, range:(0.1-0.2)*operating_labor_cost[8]
    factor_administration_costs_fci= 0.009,
    factor_administration_costs_lc=0.177,#0.177*operating_labor_cost and 0.09*FCI[8]
    factor_plant_overhead_fci = 0.708,#0.708*operating_labor_cost + 0.036*FCI[8]
    factor_plant_overhead_lc = 0.306)#[8]      
    return tea_azelaic_baseline


        
#References    
#[1]https://doi.org/10.1016/j.fuproc.2009.04.017
#[2]https://taxfoundation.org/data/all/state/combined-federal-state-corporate-tax-rates-2022/
#[3]https://www.tax-rates.org/taxtables/income-tax-by-state
#[4]https://doi.org/10.1002/bbb.1640 
#[5]https://www.bls.gov/iag/tgs/iag325.htm#earnings
#[6]https://doi.org/10.1016/j.indcrop.2020.112411
#[7]Warren Sider
#[8]# Ref(Turton et al., 2013)
#[9]https://toolbox.tlv.com/global/US/calculator/steam-table-pressure.html
 

