# -*- coding: utf-8 -*-
"""
Created on Wed Sep  6 09:46:35 2023

@author: lavan
"""


#ranges based on https://www.sciencedirect.com/science/article/pii/B9780128229125000071#bbb0195
#high oleic soybean oil composition

# ooo = np.linspace(75,85,10,dtype = int)
# lll = np.linspace(10,1,9,dtype = int)
# lnlnln = np.linspace(9,1,8,dtype = int)
# ppp = np.linspace(8,4,4,dtype = int)
# sss = np.linspace(6,2,4, dtype = int)


# tag = []
# for o in ooo:
#     tag.append([])
#     for p in ppp:
#         for l in lll:
#             for s in sss:
#                 for ln in lnlnln:
#                     sumi = o+p+l+ln+s
#                     if int(sumi) == 98:
#                         tag[-1].append({'PPP':p,'SSS':s,'OOO':o,'LLL':l,'LnLnLn':ln})
                        
#hoysoy commercial varieties


# hoysoy_commercial_vari =  {'Commercial': {'PPP': 11, 'SSS': 4, 'OOO': 22, 'LLL': 55,'LnLnLn':8},
#                            'Vistive gold': {'PPP': 3,  'SSS': 4, 'OOO': 72, 'LLL': 16,'LnLnLn':3},
#                            'Plenish': {'PPP': 6,  'SSS': 4, 'OOO': 76, 'LLL': 7, 'LnLnLn':2},
#                            'Calyno': {'PPP': 7,  'SSS': 3, 'OOO': 78, 'LLL': 3, 'LnLnLn':4},
#                            'Soyoleic':{'PPP': 7,  'SSS': 4, 'OOO': 81, 'LLL': 6, 'LnLnLn':2},
#                            'Veri':{'PPP': 7,  'SSS': 4, 'OOO': 77, 'LLL': 9, 'LnLnLn':1}}

factor_commercial = 98/100
factor_vistive = 1
factor_plenish = 98/95
factor_calyno =  98/95
factor_soyoleic = 98/100
factor_veri = 98/100
hoysoy_vari_adjusted =  {
    # 'Commercial': {'PPP': 11*factor_commercial,
                                        # 'SSS': 4*factor_commercial, 
                                        # 'OOO': 22*factor_commercial,
                                        # 'LLL': 55*factor_commercial,
                                        # 'LnLnLn':8*factor_commercial,
                                        # 'PL': 1,
                                        # 'MAG':0,
                                        # 'DAG':0,
                                        # 'Water':0.05,
                                        # 'Oleic_acid':0.95},
                          'Vistive gold': {'PPP': 3*factor_vistive, 
                                           'SSS': 4*factor_vistive, 
                                           'OOO': 72*factor_vistive,
                                           'LLL': 16*factor_vistive,
                                           'LnLnLn':3*factor_vistive,
                                          
                                           },
                           'Plenish': {'PPP': 6*factor_plenish,
                                       'SSS': 4*factor_plenish, 
                                       'OOO': 76*factor_plenish,
                                       'LLL': 7*factor_plenish,
                                       'LnLnLn':2*factor_plenish,
                                       },
                           'Calyno': {'PPP': 7*factor_calyno,
                                      'SSS': 3*factor_calyno,
                                      'OOO': 78*factor_calyno, 
                                      'LLL': 3*factor_calyno,
                                      'LnLnLn':4*factor_calyno,

                                      },
                           'Soyoleic':{'PPP': 7*factor_soyoleic, 
                                       'SSS': 4*factor_soyoleic,
                                       'OOO': 81*factor_soyoleic,
                                       'LLL': 6*factor_soyoleic,
                                       'LnLnLn':2*factor_soyoleic,
                                       },
                                       
                           'Veri':{'PPP': 7*factor_veri, 
                                   'SSS': 4*factor_veri,
                                   'OOO': 77*factor_veri, 
                                   'LLL': 9*factor_veri,
                                   'LnLnLn':1*factor_veri,
                                   }}


                        
hoysoy_fcc_tag_combos = [
  # {'PPP': 8, 'SSS': 4, 'OOO': 75, 'LLL': 10, 'LnLnLn': 1},
  # {'PPP': 8, 'SSS': 3, 'OOO': 75, 'LLL': 10, 'LnLnLn': 2},
  # {'PPP': 8, 'SSS': 2, 'OOO': 75, 'LLL': 10, 'LnLnLn': 3},
   {'PPP': 8, 'SSS': 6, 'OOO': 75, 'LLL': 8, 'LnLnLn': 1},
   {'PPP': 8, 'SSS': 4, 'OOO': 75, 'LLL': 8, 'LnLnLn': 3},
   {'PPP': 8, 'SSS': 3, 'OOO': 75, 'LLL': 8, 'LnLnLn': 4},
   {'PPP': 8, 'SSS': 2, 'OOO': 75, 'LLL': 8, 'LnLnLn': 5}]
  # {'PPP': 8, 'SSS': 6, 'OOO': 75, 'LLL': 7, 'LnLnLn': 2},
  # {'PPP': 8, 'SSS': 4, 'OOO': 75, 'LLL': 7, 'LnLnLn': 4},
  # {'PPP': 8, 'SSS': 3, 'OOO': 75, 'LLL': 7, 'LnLnLn': 5},
  # {'PPP': 8, 'SSS': 2, 'OOO': 75, 'LLL': 7, 'LnLnLn': 6},
  # {'PPP': 8, 'SSS': 6, 'OOO': 75, 'LLL': 6, 'LnLnLn': 3},
  # {'PPP': 8, 'SSS': 4, 'OOO': 75, 'LLL': 6, 'LnLnLn': 5},
  # {'PPP': 8, 'SSS': 3, 'OOO': 75, 'LLL': 6, 'LnLnLn': 6},
  # {'PPP': 8, 'SSS': 2, 'OOO': 75, 'LLL': 6, 'LnLnLn': 7},
  # {'PPP': 8, 'SSS': 6, 'OOO': 75, 'LLL': 5, 'LnLnLn': 4},
  # {'PPP': 8, 'SSS': 4, 'OOO': 75, 'LLL': 5, 'LnLnLn': 6},
  # {'PPP': 8, 'SSS': 3, 'OOO': 75, 'LLL': 5, 'LnLnLn': 7},
  # {'PPP': 8, 'SSS': 6, 'OOO': 75, 'LLL': 4, 'LnLnLn': 5},
  # {'PPP': 8, 'SSS': 4, 'OOO': 75, 'LLL': 4, 'LnLnLn': 7},
  # {'PPP': 8, 'SSS': 2, 'OOO': 75, 'LLL': 4, 'LnLnLn': 9},
  # {'PPP': 8, 'SSS': 6, 'OOO': 75, 'LLL': 3, 'LnLnLn': 6},
  # {'PPP': 8, 'SSS': 3, 'OOO': 75, 'LLL': 3, 'LnLnLn': 9},
  # {'PPP': 8, 'SSS': 6, 'OOO': 75, 'LLL': 2, 'LnLnLn': 7},
  # {'PPP': 8, 'SSS': 4, 'OOO': 75, 'LLL': 2, 'LnLnLn': 9}]
   # {'PPP': 6, 'SSS': 6, 'OOO': 75, 'LLL': 10, 'LnLnLn': 1},
   # {'PPP': 6, 'SSS': 4, 'OOO': 75, 'LLL': 10, 'LnLnLn': 3},
   # {'PPP': 6, 'SSS': 3, 'OOO': 75, 'LLL': 10, 'LnLnLn': 4},
   # {'PPP': 6, 'SSS': 2, 'OOO': 75, 'LLL': 10, 'LnLnLn': 5},
   # {'PPP': 6, 'SSS': 6, 'OOO': 75, 'LLL': 8, 'LnLnLn': 3},
   # {'PPP': 6, 'SSS': 4, 'OOO': 75, 'LLL': 8, 'LnLnLn': 5},
   # {'PPP': 6, 'SSS': 3, 'OOO': 75, 'LLL': 8, 'LnLnLn': 6},
   # {'PPP': 6, 'SSS': 2, 'OOO': 75, 'LLL': 8, 'LnLnLn': 7},
   # {'PPP': 6, 'SSS': 6, 'OOO': 75, 'LLL': 7, 'LnLnLn': 4},
   # {'PPP': 6, 'SSS': 4, 'OOO': 75, 'LLL': 7, 'LnLnLn': 6},
   # {'PPP': 6, 'SSS': 3, 'OOO': 75, 'LLL': 7, 'LnLnLn': 7},
   # {'PPP': 6, 'SSS': 6, 'OOO': 75, 'LLL': 6, 'LnLnLn': 5},
   # {'PPP': 6, 'SSS': 4, 'OOO': 75, 'LLL': 6, 'LnLnLn': 7},
   # {'PPP': 6, 'SSS': 2, 'OOO': 75, 'LLL': 6, 'LnLnLn': 9},
   # {'PPP': 6, 'SSS': 6, 'OOO': 75, 'LLL': 5, 'LnLnLn': 6},
   # {'PPP': 6, 'SSS': 3, 'OOO': 75, 'LLL': 5, 'LnLnLn': 9},
   # {'PPP': 6, 'SSS': 6, 'OOO': 75, 'LLL': 4, 'LnLnLn': 7},
   # {'PPP': 6, 'SSS': 4, 'OOO': 75, 'LLL': 4, 'LnLnLn': 9},
   # {'PPP': 6, 'SSS': 6, 'OOO': 75, 'LLL': 2, 'LnLnLn': 9},
   # {'PPP': 5, 'SSS': 6, 'OOO': 75, 'LLL': 10, 'LnLnLn': 2},
   # {'PPP': 5, 'SSS': 4, 'OOO': 75, 'LLL': 10, 'LnLnLn': 4},
   # {'PPP': 5, 'SSS': 3, 'OOO': 75, 'LLL': 10, 'LnLnLn': 5},
   # {'PPP': 5, 'SSS': 2, 'OOO': 75, 'LLL': 10, 'LnLnLn': 6},
   # {'PPP': 5, 'SSS': 6, 'OOO': 75, 'LLL': 8, 'LnLnLn': 4},
   # {'PPP': 5, 'SSS': 4, 'OOO': 75, 'LLL': 8, 'LnLnLn': 6},
   # {'PPP': 5, 'SSS': 3, 'OOO': 75, 'LLL': 8, 'LnLnLn': 7},
   # {'PPP': 5, 'SSS': 6, 'OOO': 75, 'LLL': 7, 'LnLnLn': 5},
   # {'PPP': 5, 'SSS': 4, 'OOO': 75, 'LLL': 7, 'LnLnLn': 7},
   # {'PPP': 5, 'SSS': 2, 'OOO': 75, 'LLL': 7, 'LnLnLn': 9},
   # {'PPP': 5, 'SSS': 6, 'OOO': 75, 'LLL': 6, 'LnLnLn': 6},
   # {'PPP': 5, 'SSS': 3, 'OOO': 75, 'LLL': 6, 'LnLnLn': 9},
   # {'PPP': 5, 'SSS': 6, 'OOO': 75, 'LLL': 5, 'LnLnLn': 7},
   # {'PPP': 5, 'SSS': 4, 'OOO': 75, 'LLL': 5, 'LnLnLn': 9},
   # {'PPP': 5, 'SSS': 6, 'OOO': 75, 'LLL': 3, 'LnLnLn': 9},
   # {'PPP': 4, 'SSS': 6, 'OOO': 75, 'LLL': 10, 'LnLnLn': 3},
   # {'PPP': 4, 'SSS': 4, 'OOO': 75, 'LLL': 10, 'LnLnLn': 5},
   # {'PPP': 4, 'SSS': 3, 'OOO': 75, 'LLL': 10, 'LnLnLn': 6},
   # {'PPP': 4, 'SSS': 2, 'OOO': 75, 'LLL': 10, 'LnLnLn': 7},
   # {'PPP': 4, 'SSS': 6, 'OOO': 75, 'LLL': 8, 'LnLnLn': 5},
   # {'PPP': 4, 'SSS': 4, 'OOO': 75, 'LLL': 8, 'LnLnLn': 7},
   # {'PPP': 4, 'SSS': 2, 'OOO': 75, 'LLL': 8, 'LnLnLn': 9},
   # {'PPP': 4, 'SSS': 6, 'OOO': 75, 'LLL': 7, 'LnLnLn': 6},
   # {'PPP': 4, 'SSS': 3, 'OOO': 75, 'LLL': 7, 'LnLnLn': 9},
   # {'PPP': 4, 'SSS': 6, 'OOO': 75, 'LLL': 6, 'LnLnLn': 7},
   # {'PPP': 4, 'SSS': 4, 'OOO': 75, 'LLL': 6, 'LnLnLn': 9},
   # {'PPP': 4, 'SSS': 6, 'OOO': 75, 'LLL': 4, 'LnLnLn': 9}]
   
  #  {'PPP': 8, 'SSS': 3, 'OOO': 76, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 76, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 76, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 76, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 76, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 76, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 76, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 76, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 76, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 76, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 76, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 76, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 76, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 76, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 76, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 76, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 76, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 76, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 76, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 76, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 76, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 76, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 76, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 76, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 76, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 76, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 76, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 76, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 76, 'LLL': 10, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 76, 'LLL': 10, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 76, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 76, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 76, 'LLL': 8, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 76, 'LLL': 8, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 76, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 76, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 76, 'LLL': 7, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 76, 'LLL': 7, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 76, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 76, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 76, 'LLL': 6, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 76, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 76, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 76, 'LLL': 5, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 76, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 76, 'LLL': 4, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 76, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 76, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 76, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 76, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 76, 'LLL': 10, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 76, 'LLL': 10, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 76, 'LLL': 10, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 76, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 76, 'LLL': 8, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 76, 'LLL': 8, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 76, 'LLL': 8, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 76, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 76, 'LLL': 7, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 76, 'LLL': 7, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 76, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 76, 'LLL': 6, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 76, 'LLL': 6, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 76, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 76, 'LLL': 5, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 76, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 76, 'LLL': 4, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 76, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 76, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 76, 'LLL': 10, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 76, 'LLL': 10, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 76, 'LLL': 10, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 76, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 76, 'LLL': 8, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 76, 'LLL': 8, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 76, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 76, 'LLL': 7, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 76, 'LLL': 7, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 76, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 76, 'LLL': 6, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 76, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 76, 'LLL': 5, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 76, 'LLL': 3, 'LnLnLn': 9},
  # {'PPP': 8, 'SSS': 2, 'OOO': 77, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 77, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 77, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 77, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 77, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 77, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 77, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 77, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 77, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 77, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 77, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 77, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 77, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 77, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 77, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 77, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 77, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 77, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 77, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 77, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 77, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 77, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 77, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 77, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 77, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 77, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 77, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 77, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 77, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 77, 'LLL': 10, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 77, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 77, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 77, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 77, 'LLL': 8, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 77, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 77, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 77, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 77, 'LLL': 7, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 77, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 77, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 77, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 77, 'LLL': 6, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 77, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 77, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 77, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 77, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 77, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 77, 'LLL': 4, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 77, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 77, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 77, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 77, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 77, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 77, 'LLL': 10, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 77, 'LLL': 10, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 77, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 77, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 77, 'LLL': 8, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 77, 'LLL': 8, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 77, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 77, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 77, 'LLL': 7, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 77, 'LLL': 7, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 77, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 77, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 77, 'LLL': 6, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 77, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 77, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 77, 'LLL': 5, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 77, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 77, 'LLL': 4, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 77, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 77, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 77, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 77, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 77, 'LLL': 10, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 77, 'LLL': 10, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 77, 'LLL': 10, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 77, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 77, 'LLL': 8, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 77, 'LLL': 8, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 77, 'LLL': 8, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 77, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 77, 'LLL': 7, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 77, 'LLL': 7, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 77, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 77, 'LLL': 6, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 77, 'LLL': 6, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 77, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 77, 'LLL': 5, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 77, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 77, 'LLL': 4, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 77, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 78, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 78, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 78, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 78, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 78, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 78, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 78, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 78, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 78, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 78, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 78, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 78, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 78, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 78, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 78, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 78, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 78, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 78, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 78, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 78, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 78, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 78, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 78, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 78, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 78, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 78, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 78, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 78, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 78, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 78, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 78, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 78, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 78, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 78, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 78, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 78, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 78, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 78, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 78, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 78, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 78, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 78, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 78, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 78, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 78, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 78, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 78, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 78, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 78, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 78, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 78, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 78, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 78, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 78, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 78, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 78, 'LLL': 10, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 78, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 78, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 78, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 78, 'LLL': 8, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 78, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 78, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 78, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 78, 'LLL': 7, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 78, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 78, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 78, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 78, 'LLL': 6, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 78, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 78, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 78, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 78, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 78, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 78, 'LLL': 4, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 78, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 78, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 78, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 78, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 78, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 78, 'LLL': 10, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 78, 'LLL': 10, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 78, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 78, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 78, 'LLL': 8, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 78, 'LLL': 8, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 78, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 78, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 78, 'LLL': 7, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 78, 'LLL': 7, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 78, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 78, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 78, 'LLL': 6, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 78, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 78, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 78, 'LLL': 5, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 78, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 78, 'LLL': 4, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 78, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 78, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 78, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 79, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 79, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 79, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 79, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 79, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 79, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 79, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 79, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 79, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 79, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 79, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 79, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 79, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 79, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 79, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 79, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 79, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 79, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 79, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 79, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 79, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 79, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 79, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 79, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 79, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 79, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 79, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 79, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 79, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 79, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 79, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 79, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 79, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 79, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 79, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 79, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 79, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 79, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 79, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 79, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 79, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 79, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 79, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 79, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 79, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 79, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 79, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 79, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 79, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 79, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 79, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 79, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 79, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 79, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 79, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 79, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 79, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 79, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 79, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 79, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 79, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 79, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 79, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 79, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 79, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 79, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 79, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 79, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 79, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 79, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 79, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 79, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 79, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 79, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 79, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 79, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 79, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 79, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 79, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 79, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 79, 'LLL': 10, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 79, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 79, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 79, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 79, 'LLL': 8, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 79, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 79, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 79, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 79, 'LLL': 7, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 79, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 79, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 79, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 79, 'LLL': 6, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 79, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 79, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 79, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 79, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 79, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 79, 'LLL': 4, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 79, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 79, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 79, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 79, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 80, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 80, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 80, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 80, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 80, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 80, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 80, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 80, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 80, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 80, 'LLL': 3, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 80, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 80, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 80, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 80, 'LLL': 2, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 80, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 80, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 80, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 80, 'LLL': 1, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 80, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 80, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 80, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 80, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 80, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 80, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 80, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 80, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 80, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 80, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 80, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 80, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 80, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 80, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 80, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 80, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 80, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 80, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 80, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 80, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 80, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 80, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 80, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 80, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 80, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 80, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 80, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 80, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 80, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 80, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 80, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 80, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 80, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 80, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 80, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 80, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 80, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 80, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 80, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 80, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 80, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 80, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 80, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 80, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 80, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 80, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 80, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 80, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 80, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 80, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 80, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 80, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 80, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 80, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 80, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 80, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 80, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 80, 'LLL': 10, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 80, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 80, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 80, 'LLL': 8, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 80, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 80, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 80, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 80, 'LLL': 7, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 80, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 80, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 80, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 80, 'LLL': 6, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 80, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 80, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 80, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 80, 'LLL': 5, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 80, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 80, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 80, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 80, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 80, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 80, 'LLL': 3, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 80, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 80, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 80, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 80, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 81, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 81, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 81, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 81, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 81, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 81, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 81, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 81, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 81, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 81, 'LLL': 2, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 81, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 81, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 81, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 81, 'LLL': 1, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 81, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 81, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 81, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 81, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 81, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 81, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 81, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 81, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 81, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 81, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 81, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 81, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 81, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 81, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 81, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 81, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 81, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 81, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 81, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 81, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 81, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 81, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 81, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 81, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 81, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 81, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 81, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 81, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 81, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 81, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 81, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 81, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 81, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 81, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 81, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 81, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 81, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 81, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 81, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 81, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 81, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 81, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 81, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 81, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 81, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 81, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 81, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 81, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 81, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 81, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 81, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 81, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 81, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 81, 'LLL': 10, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 81, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 81, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 81, 'LLL': 8, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 81, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 81, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 81, 'LLL': 7, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 81, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 81, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 81, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 81, 'LLL': 6, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 81, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 81, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 81, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 81, 'LLL': 5, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 81, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 81, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 81, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 81, 'LLL': 4, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 81, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 81, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 81, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 81, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 81, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 81, 'LLL': 2, 'LnLnLn': 9},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 81, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 81, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 82, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 82, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 82, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 82, 'LLL': 3, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 82, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 82, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 82, 'LLL': 2, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 82, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 82, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 6, 'OOO': 82, 'LLL': 1, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 82, 'LLL': 1, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 82, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 82, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 82, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 82, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 82, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 82, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 82, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 82, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 82, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 82, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 82, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 82, 'LLL': 3, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 82, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 82, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 82, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 82, 'LLL': 2, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 82, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 82, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 82, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 82, 'LLL': 1, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 82, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 82, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 82, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 82, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 82, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 82, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 82, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 82, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 82, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 82, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 82, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 82, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 82, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 82, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 82, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 82, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 82, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 82, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 82, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 82, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 82, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 82, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 82, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 82, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 82, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 82, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 82, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 82, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 82, 'LLL': 8, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 82, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 82, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 82, 'LLL': 7, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 82, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 82, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 82, 'LLL': 6, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 82, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 82, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 82, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 82, 'LLL': 5, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 82, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 82, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 82, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 82, 'LLL': 4, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 82, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 82, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 82, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 82, 'LLL': 3, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 82, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 82, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 82, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 82, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 82, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 82, 'LLL': 1, 'LnLnLn': 9},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 83, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 83, 'LLL': 3, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 83, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 83, 'LLL': 2, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 83, 'LLL': 2, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 83, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 4, 'OOO': 83, 'LLL': 1, 'LnLnLn': 2},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 83, 'LLL': 1, 'LnLnLn': 3},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 83, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 83, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 83, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 83, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 83, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 83, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 83, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 83, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 83, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 83, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 83, 'LLL': 2, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 83, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 83, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 83, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 6, 'OOO': 83, 'LLL': 1, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 83, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 83, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 83, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 83, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 83, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 83, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 83, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 83, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 83, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 83, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 83, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 83, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 83, 'LLL': 3, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 83, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 83, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 83, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 83, 'LLL': 2, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 83, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 83, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 83, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 83, 'LLL': 1, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 83, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 83, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 83, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 83, 'LLL': 8, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 83, 'LLL': 7, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 83, 'LLL': 7, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 83, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 83, 'LLL': 6, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 83, 'LLL': 6, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 83, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 83, 'LLL': 5, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 83, 'LLL': 5, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 83, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 83, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 83, 'LLL': 4, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 83, 'LLL': 4, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 83, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 83, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 83, 'LLL': 3, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 83, 'LLL': 3, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 83, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 83, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 83, 'LLL': 2, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 83, 'LLL': 2, 'LnLnLn': 7},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 83, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 83, 'LLL': 1, 'LnLnLn': 6},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 83, 'LLL': 1, 'LnLnLn': 7},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 85, 'LLL': 2, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 3, 'OOO': 85, 'LLL': 1, 'LnLnLn': 1},
  #  {'PPP': 8, 'SSS': 2, 'OOO': 85, 'LLL': 1, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 85, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 85, 'LLL': 3, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 85, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 85, 'LLL': 2, 'LnLnLn': 1},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 85, 'LLL': 2, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 85, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 4, 'OOO': 85, 'LLL': 1, 'LnLnLn': 2},
  #  {'PPP': 6, 'SSS': 3, 'OOO': 85, 'LLL': 1, 'LnLnLn': 3},
  #  {'PPP': 6, 'SSS': 2, 'OOO': 85, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 85, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 85, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 85, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 85, 'LLL': 3, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 85, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 85, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 85, 'LLL': 2, 'LnLnLn': 2},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 85, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 85, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 6, 'OOO': 85, 'LLL': 1, 'LnLnLn': 1},
  #  {'PPP': 5, 'SSS': 4, 'OOO': 85, 'LLL': 1, 'LnLnLn': 3},
  #  {'PPP': 5, 'SSS': 3, 'OOO': 85, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 5, 'SSS': 2, 'OOO': 85, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 85, 'LLL': 6, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 85, 'LLL': 5, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 85, 'LLL': 5, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 85, 'LLL': 4, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 85, 'LLL': 4, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 85, 'LLL': 4, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 85, 'LLL': 3, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 85, 'LLL': 3, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 85, 'LLL': 3, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 85, 'LLL': 2, 'LnLnLn': 1},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 85, 'LLL': 2, 'LnLnLn': 3},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 85, 'LLL': 2, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 85, 'LLL': 2, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 6, 'OOO': 85, 'LLL': 1, 'LnLnLn': 2},
  #  {'PPP': 4, 'SSS': 4, 'OOO': 85, 'LLL': 1, 'LnLnLn': 4},
  #  {'PPP': 4, 'SSS': 3, 'OOO': 85, 'LLL': 1, 'LnLnLn': 5},
  #  {'PPP': 4, 'SSS': 2, 'OOO': 85, 'LLL': 1, 'LnLnLn': 6}]
